microsoft/XamlBehaviorsWpf

src/Microsoft.Xaml.Behaviors/Core/LaunchUriOrFileAction.cs
Although dotnet core 3.0 is not supported, this change will at least solve #8 
I can image that there are cases where UseShellExecute doesn't make sense, with UWP this should be false.
But this library is only for .NET Framework and has a potential target in dotnet core 3.0, so from my point of view the fix doesn't to be more complex... just enable it!
=> Enable UseShellExecute to fix LaunchUriOrFileAction

src/Microsoft.Xaml.Behaviors/Microsoft.Xaml.Behaviors.csproj
*.DesignTools assembly reference was preventing building .NET WPF project in Blend.
None
=> Fix Extensibility assembly cause build error in Blend

Test/UnitTests/UnitTests.csproj, version.json
* Updated version.json to use 1.1 version number. 
* Updated NuGet test framework references. 
* Removed NuGet package reference to Microsoft.NET.Test.Sdk, as it is preventing NuGet restore in pipeline.
[https://github.com/microsoft/XamlBehaviorsWpf/issues/55](https://github.com/microsoft/XamlBehaviorsWpf/issues/55)
None
=> Bug #55 Assembly version number incorrect.

src/Microsoft.Xaml.Behaviors.DesignTools/MetadataTableProvider.cs, src/Microsoft.Xaml.Behaviors.DesignTools/Microsoft.Xaml.Behaviors.DesignTools.csproj, src/Microsoft.Xaml.Behaviors/Microsoft.Xaml.Behaviors.csproj
Added support for rich property editors in the Properties view.
None
Specialized property editors are now displayed in the Properties view in Blend.
=> Add rich property editor support for .NET Core projects

src/BehaviorsSdk.sln, src/Microsoft.Xaml.Behaviors.Design/MetadataTableProvider.DesignerIsolation.cs, src/Microsoft.Xaml.Behaviors.Design/Microsoft.Xaml.Behaviors.Design.csproj, src/Microsoft.Xaml.Behaviors.Design/Properties/AssemblyInfo.cs, src/Microsoft.Xaml.Behaviors.Design/Properties/Resources.Designer.cs, src/Microsoft.Xaml.Behaviors.DesignTools/MetadataTableProvider.SurfaceIsolation.cs, src/Microsoft.Xaml.Behaviors.DesignTools/MetadataTableProvider.cs, src/Microsoft.Xaml.Behaviors.DesignTools/Microsoft.Xaml.Behaviors.DesignTools.csproj, src/Microsoft.Xaml.Behaviors.DesignTools/Properties/Resources.Designer.cs, src/Microsoft.Xaml.Behaviors/Install.ps1, src/Microsoft.Xaml.Behaviors/Microsoft.Xaml.Behaviors.csproj
Includes a new Design project for .NET Framework applications, which targets the Designer Isolation architecture.
NuGet package includes an Install.ps1 powershell script that removes the reference to the .Design.dll when adding package to .NET Framework projects. 
No public API changes.
Value editors now appear in the property grid when editing behavior properties, such as the SourceObject of the EventTrigger.
=> Add rich property editors for design-time experience in WPF .NET Framework applications

src/Microsoft.Xaml.Behaviors.Design/Microsoft.Xaml.Behaviors.Design.csproj, src/Microsoft.Xaml.Behaviors.DesignTools/MetadataTableProvider.cs, src/Microsoft.Xaml.Behaviors.DesignTools/Microsoft.Xaml.Behaviors.DesignTools.csproj
Changing framework target version of design-time projects to v4.5. There is currently an issue with the pipeline build, which was fixed by targetting v4.7.2. However the projects must target v4.5.
=> Fix issue with build failing in pipeline

src/Microsoft.Xaml.Behaviors/Core/DataTrigger.cs
Online 43 of the `DataTrigger.cs` file, added an event handler for the `Loaded` event of the AssociatedObject. Within this handler, we call `EvaluateBindingChange` to force the evaluation of the binding value when the element first loads.  After the element is loaded and the bindings have been evaluated, we immediately unhook the `Loaded` event handler.
Note: tests were not added because I was unable to simulate a loaded event on a UI component. This was tested with a running sample.
- #11
None
When an element first loads, the binding value is now evaluated by the DataTrigger.
=> DataTrigger: Evaluate initial value on element load

README.md, Test/UnitTests/BehaviorUtilities.cs, Test/UnitTests/ChangePropertyActionTests.cs, Test/UnitTests/UnitTests.csproj, src/Microsoft.Xaml.Behaviors/Microsoft.Xaml.Behaviors.csproj
This PR adds the target framework for .Net Core 3.1.
Closes #78 
Added:
- netcoreapp3.1 target framework
-/-
=> Add target framework for .Net Core 3.1

.github/workflows/main.yml, Test/UnitTests/UnitTests.csproj, azure-pipelines.yml, src/Microsoft.Xaml.Behaviors/Microsoft.Xaml.Behaviors.csproj
This PR adds the target framework for .Net 5.0.
Closes #80 
Added:
- net5.0-windows target framework
-/-
Should we drop the netcoreapp3.0 target?
=> Add .Net 5.0 target

src/Microsoft.Xaml.Behaviors/VisualStateUtilities.cs
Remove unnecessary comment to trigger new build version.
We are trying to update the symbols in the nuget packages to be non-portable .pdbs so that they resolve with symchk. We've changed the msbuild arguments in the release pipeline to achieve this. Since there is no code change, we are unable to generate a newer nuget package version. Hence this PR. Since the build versions and subsequently, the nugetpackage versions are controlled by Nerdbank.GitVersioning, this is the only way to trigger a newer build version.
=> Remove unnessary return statement to trigger new build version

.editorconfig, Test/UnitTests/UnitTests.csproj, samples/XAMLBehaviorsSample/XAMLBehaviorsSample/App.config, samples/XAMLBehaviorsSample/XAMLBehaviorsSample/Properties/Resources.Designer.cs, samples/XAMLBehaviorsSample/XAMLBehaviorsSample/Properties/Settings.Designer.cs, samples/XAMLBehaviorsSample/XAMLBehaviorsSample/XAMLBehaviorsSample.csproj, src/Microsoft.Xaml.Behaviors.Design/Microsoft.Xaml.Behaviors.Design.csproj, src/Microsoft.Xaml.Behaviors/Microsoft.Xaml.Behaviors.csproj
Upgraded the project to .NET 4.6.2 as .NET 4.5 is no longer supported.
=> Upgrade to .NET 4.6.2

Test/UnitTests/EventTriggerTests.cs, Test/UnitTests/KeyTriggerTest.cs, Test/UnitTests/UnitTests.csproj, src/Microsoft.Xaml.Behaviors/EventTriggerBase.cs, src/Microsoft.Xaml.Behaviors/Input/KeyTrigger.cs
Fixed #107.
KeyTrigger would fire multiple times due to the Loaded event being invoked multiple times. This would cause the KeyUp/KeyDown events to be registered multiple times and therefore invoke the trigger multiple times.
Added code to remove the `Loaded` event handler from the source object to prevent the Loaded event from firing multiple times.
- #107
List all API changes here (or just put None), example:
Changed:
- private void UnregisterLoaded() => protected void UnregisterLoaded()
=> Fixed #107

Test/UnitTests/KeyTriggerTest.cs, src/Microsoft.Xaml.Behaviors/Input/KeyTrigger.cs
Modified the KeyTrigger `OnKeyPress` method to properly handle modifier keys.
- #77
=> Fixed KeyTrigger modifier keys

.github/workflows/main.yml, Test/UnitTests/UnitTests.csproj, src/Microsoft.Xaml.Behaviors/Microsoft.Xaml.Behaviors.csproj
Added support for .NET 6.0 since it is LTS.
Dropped support for .NET 5.0 as it out of official support.
Also added a reference to the `Microsoft.NET.Test.Sdk` nuget package so the unit tests will run for .NET Core 3.1 and .NET 6.
- #102
=> Upgrade Behaviors to .NET 6.0

.github/workflows/main.yml, src/Microsoft.Xaml.Behaviors/Microsoft.Xaml.Behaviors.csproj
I am adding the unit tests to the GitHub Action
- #120
=> Adding tests to GitHub Action

Test/UnitTests/UnitTests.csproj, src/Microsoft.Xaml.Behaviors/Microsoft.Xaml.Behaviors.csproj
Since we no longer support .NET Core 3.1 or .NET 5, the need for the MSBuild.Sdk.Extras is no longer required.
Changed the Behaviors and UnitTests project to use the official Microsoft.NET.Sdk
- #126
=> Removed use of MSBuild.Sdk.Extras

Test/UnitTests/EventTriggerTests.cs
- Updated TestLoadedEvent to use Click instead of mouse capture
- Corrected the order of expected vs actual for Assert.AreEqual()
Fixes #128
=> Updated EventTriggerTests

src/Microsoft.Xaml.Behaviors/TriggerCollection.cs
Make TriggerCollection constructor public.
Fixes #103 
Changed:
- internal TriggerCollection() => public TriggerCollection()
=> Make TriggerCollection constructor public

src/Microsoft.Xaml.Behaviors.Design/Microsoft.Xaml.Behaviors.Design.csproj, src/Microsoft.Xaml.Behaviors.DesignTools/Microsoft.Xaml.Behaviors.DesignTools.csproj, src/Microsoft.Xaml.Behaviors/Microsoft.Xaml.Behaviors.csproj
Modified the build output path of the DesignTools projects from the old `net45` to `net462` due to the recent framework upgrades.
- Related to work done for #102
=> Updated DesignTools project's output path

src/Microsoft.Xaml.Behaviors/Microsoft.Xaml.Behaviors.csproj
Added the DesignTools.dll to the net462 TFM so that the designers would load when working with a net462 project in VS2022.
- Fixes #132
=> Added DesignTools.dll to net462 TFM

Test/UnitTests/BehaviorUtilities.cs, src/Microsoft.Xaml.Behaviors/Core/ExtendedVisualStateManager.cs, src/Microsoft.Xaml.Behaviors/Microsoft.Xaml.Behaviors.csproj, src/Microsoft.Xaml.Behaviors/packages.config
Removed unneeded references in the csproj file. Since we are using SDK style projects, we no longer need to explicitly include the net462 assembly references
Added an additional 1591 as a `NoWarn`. We have a number of public properties an methods with no XML documentation. Until an effort is made to add them, the 1591 warning is pointless.
Removed the no longer needed packages.config file.
=> House Keeping

src/Microsoft.Xaml.Behaviors/Install.ps1
Just like `Microsoft.Xaml.Behaviors.Design`, the `Microsoft.Xaml.Behaviors.DesignTools` reference also needs to be removed in install.ps1.
Fixes #142
=> Remove Microsoft.Xaml.Behaviors.DesignTools in install.ps1

samples/XAMLBehaviorsSample/XAMLBehaviorsSample/InvokeCommandControl.xaml, samples/XAMLBehaviorsSample/XAMLBehaviorsSample/InvokeCommandControl.xaml.cs
Fixing the broken binding that was always passing `null` into the command.   Explicitly stated the element name and then passed in the 'Background' property.   Cast the parameter in the code behind with the Command
This should fix the issue found in (Issue #144)[https://github.com/microsoft/XamlBehaviorsWpf/issues/144].
Changed:
- void Execute(object parameter)
- InvokeCommandControl.xaml
No changes to behavior are expected.
=> Updating the command parameter binding for the ColorCommand property so null isn't being passed as the parameter value.

azure-pipelines/build.yml
Migrated from Classic Azure Pipelines to 1ES template
- Provide links to bugs here
N/A
N/A
=> Added azure-pipelines/build.yml

Directory.Build.props, azure-pipelines/build.yml, src/Microsoft.Xaml.Behaviors.Signing.targets
- Default DelaySign to false
- Use SignType=real when Build.OfficialRelease=true
- Explicitly pass /p:SignType=$(SignType) in the msbuild command
- Remove <SignAssembly>true</SignAssembly> from Directory.Build.props. This conflicts with the Signing.targets
=> Attempt to fix build signing errors

src/Microsoft.Xaml.Behaviors.Signing.targets
Turns out this wasn't the cause of the build signing issues.
=> Re-enable DelaySign

Directory.Build.props, azure-pipelines/build.yml
Enable diagnostic logging to help track down signing issues.
=> Diagnostic logging for builds

Directory.Build.props
THese are needed or the UnitTest project fails to build.
=> Re-add Directory.Build.props

src/Microsoft.Xaml.Behaviors/AssemblyInfo.cs, src/Microsoft.Xaml.Behaviors/Microsoft.Xaml.Behaviors.csproj
May fix the signing issue.
Trevor recommended these fixes as a way to solve the build/signing issue. Hopefully this works.
=> Explicitly set DelaySign=true for Microsoft.Xaml.Behaviors.dll

Test/UnitTests/KeyTriggerTest.cs, src/Microsoft.Xaml.Behaviors/Input/KeyTrigger.cs
Fixed #162 by updating the KeyTrigger logic to look for exact key/modifier key matches.
Since you cannot modify the pressed modifiers in WPF, I was not able to add a unit test for the issues discovered in #162.
I did add an additional test for the scenario when there is a modifier defined on a KeyTrigger, but that modifier is not pressed when pressing a key. In this case, the action should not execute.
=> Improved KeyTrigger logic

azure-pipelines/build.yml, version.json
We need to tell Nerdbank.GitVersioning to use main instead of master for calculations as well as defining PublicRelease=true when making a public release.
=> Fixed package versioning

azure-pipelines/build.yml
Correctly use the `publishFeedCredentials` property instead of `externalEndpoint` in order to get
publishing to NuGet.org to work correctly.
=> Use publishFeedCredentials instead of externalEndpoint

azure-pipelines/build.yml
5.8.0 is pretty old. Ideally, as long as 6.x works, we should use it.
=> Bump nuget.exe used in pipeline to 6.x

src/Microsoft.Xaml.Behaviors.DesignTools/Microsoft.Xaml.Behaviors.DesignTools.csproj, src/Microsoft.Xaml.Behaviors.DesignTools/packages.config
Describe your changes here.
- Provide links to bugs here
List all API changes here (or just put None), example:
Added:
- void SomeMethod()
Changed:
- void SomeMethod() => bool SomeMethod()
Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.
=> Replace packages.config with PackageReferences

src/Microsoft.Xaml.Behaviors/Input/KeyTrigger.cs
Fixes #175
There are not unit tests because WPF makes it impossible to simulate modifier keys in a unit test.
=> Fixed KeyTrigger where the Alt key was being seen as Key.System
